name: Build Android App
on:
  push:
    paths:
      - 'android/main_android.py'
      - 'index.html'
      - 'requirements.txt'
      - '.github/workflows/android-app.yml'
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy kivymd buildozer
      - name: Build APK with Buildozer
  run: |
    sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
    buildozer init || true
    sed -i 's|^source.include_exts =.*|source.include_exts = py,html,css,js|' buildozer.spec
    sed -i 's|^source.main =.*|source.main = android/main_android.py|' buildozer.spec
    buildozer -v android debug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app-apk
          path: bin/*.apk
