name: Build Android App

on:
  push:
    paths:
      - 'android/main_android.py'
      - 'index.html'
      - 'requirements.txt'
      - '.github/workflows/android-app.yml'

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/build-tools/34.0.0:${{ github.workspace }}/android-sdk/emulator:${{ github.workspace }}/android-sdk/tools:${{ github.workspace }}/android-sdk/tools/bin:${{ env.PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython kivy kivymd buildozer

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev openjdk-8-jdk unzip wget

      - name: Install Android SDK and tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Build APK with Buildozer
        run: |
          buildozer init || true
          sed -i 's|^source.include_exts =.*|source.include_exts = py,html,css,js|' buildozer.spec
          sed -i 's|^source.main =.*|source.main = android/main_android.py|' buildozer.spec
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app-apk
          path: bin/*.apk