name: Build Windows and Android Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies (without Kivy)
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install Flask requests pywebview
      - name: Build Windows Executable
        run: |
          pyinstaller --onefile app.py --name app_nodos
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_nodos-windows
          path: dist/app_nodos.exe

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-venv libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libgdbm-dev libbz2-dev liblzma-dev
      - name: Install Android SDK tools (Aidl)
        run: |
          sudo apt-get install -y android-sdk android-sdk-platform-tools android-sdk-build-tools
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython
      - name: Build Android APK
        run: |
          buildozer init || true
          buildozer -v android debug
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_nodos-android
          path: bin/*.apk
